export { DashboardPage} from "./DashboardPage"
export { LoginPage } from "./LoginPage"
export { RegistrationPage } from "./RegistrationPage"
export {ForggotPasswordPage} from "./ForggotPasswordPage"
export {ChangePasswordPage} from "./ChangePasswordPage"
export {TeamPage} from "./TeamPage"
export {ContactPage} from "./ContactPage"
export {SchedulePage} from "./SchedulePage"
export {MyProfilePage} from "./MyProfilePage"